name: BansPlus
main: me.Darrionat.BansPlus.Main
description: A banning plugin made simple
version: 1.0
api-version: 1.13
author: Darrionat

commands:
  ban:
    aliases: [banp]
    usage: </command> user reason
  banlist:
    aliases: [banlistp]
    usage: </command> player/ip
  bansplus:
    aliases: [banplus, bansp]
    usage: </command>
  ipban:
    aliases: [ipbanp]
    usage: </command> ip reason
  tempban:
    aliases: [tempbanp]
    usage: </command> user time reason
  unban:
    aliases: [unbanp]
    usage: </command> player/ip
  
    
permissions:
  bansplus.*:
    description: Gives access to all BansPlus commands
    children:
      bansplus.ban: true
      banplus.banlist: true
      bansplus.bansplus: true
      bansplus.ipban: true
      banplus.tempban: true
      bansplus.unban: true
  bansplus.ban:
    description: Allows a player to ban players
    default: op
  bansplus.banlist:
    description: Allows a player to read the ban list
    default: op
  bansplus.bansplus:
    description: Allows a player to read the help section
    default: op
  bansplus.ipban:
    description: Allows a player to ban an IP
    default: op
  bansplus.tempban:
    description: Allows a player to temporarily ban a player
    default: op
  bansplus.unban:
    description: Allows a player to unban a player
    default: op