name: BansPlus
main: me.Darrionat.BansPlus.Main
description: A banning plugin made simple
version: 1.3
api-version: 1.13
author: Darrionat

commands:
  ban:
    aliases: [banp]
    usage: </command> player reason
  baninfo:
    aliases: [baninfoplus]
    usage: </command> player
  banlist:
    aliases: [banlistplus]
    usage: </command> player/ip
  bansplus:
    aliases: [banplus]
    usage: </command> help/reload
  cps:
    aliases: [cpsplus]
    usage: </command> player duration
  ipban:
    aliases: [ipbanplus]
    usage: </command> ip reason
  ipbaninfo:
    aliases: [ipbaninfoplus]
    usage: </command> ip
  mute:
    aliases: [muteplus]
    usage: </command> player time reason
  muteinfo:
    aliases: [muteinfoplus]
    usage: </command> player
  mutelist:
    aliases: [mutelistplus]
    usage: </command>
  staffchat:
    aliases: [sc, scplus, staffchatplus]
    usage: </command> toggle/message
  tempban:
    aliases: [tempbanplus]
    usage: </command> player time reason
  unban:
    aliases: [unbanplus]
    usage: </command> player/ip
  unmute:
    aliases: [unmuteplus]
    usage: </command> player
  warn:
    aliases: [warnplus]
    usage: </command> player reason
permissions:
  bansplus.*:
    description: Gives access to all BansPlus commands
    children:
      bansplus.ban: true
      banplus.banlist: true
      bansplus.bansplus: true
      bansplus.cps: true
      bansplus.ipban: true
      banplus.mute: true
      bansplus.staff: true
      banplus.reload: true
      banplus.tempban: true
      bansplus.unban: true
      bansplus.unmute: true
      bansplus.warn: true
      bansplus.unbannable: true
  bansplus.ban:
    description: Allows a player to ban players
    default: op
  bansplus.baninfo:
    description: Allows a player to see info about a banned player
    default: op
  bansplus.banlist:
    description: Allows a player to read the ban list
    default: op
  bansplus.bansplus:
    description: Allows a player to read the help section
    default: op
  bansplus.cps:
    description: Allows a user to test a player for average clicks per second
    default: op
  bansplus.ipban:
    description: Allows a player to ban an IP
    default: op
  bansplus.ipbaninfo:
    description: Allows a player to see info about an IP address
    default: op
  bansplus.mute:
    description: Allows a player to mute player
    default: op
  bansplus.muteinfo:
    description: Allows a player to see info about a muted information
    default: op
  bansplus.mutelist:
    description: Allows a player to read the mute list
    default: op
  bansplus.reload:
    description: Allows a player to reload all yml files
    default: op
  bansplus.staff:
    description: Allows a player to recieve all staff messages
    default: op
  bansplus.staffchat:
    description: Allows a player to send to the staff channel
    default: op
  bansplus.tempban:
    description: Allows a player to temporarily ban a player
    default: op
  bansplus.unban:
    description: Allows a player to unban a banned player
    default: op
  bansplus.unmute:
    description: Allows a player to unmute a muted player
    default: op
  bansplus.warn:
    description: Allows a player to warn a player
    default: op
  bansplus.unbannable:
    description: Makes a player unbannable
    default: op