name: BansPlus
main: me.Darrionat.BansPlus.Main
description: A banning plugin made simple
version: 1.0
api-version: 1.13
author: Darrionat

commands:
  ban:
    aliases: [banplus]
    usage: </command> user reason
  banlist:
    aliases: [banlistplus]
    usage: </command> player/ip
  bansplus:
    aliases: [banplus]
    usage: </command>
  ipban:
    aliases: [ipbanplus]
    usage: </command> ip reason
  mute:
    aliases: [muteplus]
    usage: </command> user time reason
  tempban:
    aliases: [tempbanplus]
    usage: </command> user time reason
  unban:
    aliases: [unbanplus]
    usage: </command> player/ip
  unmute:
    aliases: [unmuteplus]
    usage: </command> player
permissions:
  bansplus.*:
    description: Gives access to all BansPlus commands
    children:
      bansplus.ban: true
      banplus.banlist: true
      bansplus.bansplus: true
      bansplus.ipban: true
      banplus.mute: true
      banplus.tempban: true
      bansplus.unban: true
      bansplus.unmute: true
  bansplus.ban:
    description: Allows a player to ban players
    default: op
  bansplus.banlist:
    description: Allows a player to read the ban list
    default: op
  bansplus.bansplus:
    description: Allows a player to read the help section
    default: op
  bansplus.ipban:
    description: Allows a player to ban an IP
    default: op
  bansplus.mute:
    description: Allows a player to mute players
    default: op
  bansplus.tempban:
    description: Allows a player to temporarily ban a player
    default: op
  bansplus.unban:
    description: Allows a player to unban a player
    default: op
  bansplus.unmute:
    description: Allows a player to unmute a player
    default: op