name: BansPlus
main: me.Darrionat.BansPlus.Main
description: A banning plugin made simple
version: 1.0
api-version: 1.13
author: Darrionat

commands:
  ban:
    aliases: [banplus]
    usage: </command> player reason
  baninfo:
    aliases: [baninfoplus]
    usage: </command> player
  banlist:
    aliases: [banlistplus]
    usage: </command> player/ip
  bansplus:
    aliases: [banplus]
    usage: </command>
  ipban:
    aliases: [ipbanplus]
    usage: </command> ip reason
  ipbaninfo:
    aliases: [ipbaninfoplus]
    usage: </command> ip
  mute:
    aliases: [muteplus]
    usage: </command> player time reason
  muteinfo:
    aliases: [muteinfoplus]
    usage: </command> player
  mutelist:
    aliases: [mutelistplus]
    usage: </command>
  tempban:
    aliases: [tempbanplus]
    usage: </command> player time reason
  unban:
    aliases: [unbanplus]
    usage: </command> player/ip
  unmute:
    aliases: [unmuteplus]
    usage: </command> player
permissions:
  bansplus.*:
    description: Gives access to all BansPlus commands
    children:
      bansplus.ban: true
      banplus.banlist: true
      bansplus.bansplus: true
      bansplus.ipban: true
      banplus.mute: true
      banplus.tempban: true
      bansplus.unban: true
      bansplus.unmute: true
  bansplus.ban:
    description: Allows a user to ban players
    default: op
  bansplus.baninfo:
    description: Allows a user to see info about a banned player
    default: op
  bansplus.banlist:
    description: Allows a user to read the ban list
    default: op
  bansplus.bansplus:
    description: Allows a user to read the help section
    default: op
  bansplus.ipban:
    description: Allows a user to ban an IP
    default: op
  bansplus.ipbaninfo:
    description: Allows a user to see info about an IP address
    default: op
  bansplus.mute:
    description: Allows a user to mute player
    default: op
  bansplus.muteinfo:
    description: Allows a user to see info about a muted information
    default: op
  bansplus.mutelist:
    description: Allows a user to read the mute list
    default: op
  bansplus.tempban:
    description: Allows a user to temporarily ban a player
    default: op
  bansplus.unban:
    description: Allows a user to unban a player
    default: op
  bansplus.unmute:
    description: Allows a user to unmute a player
    default: op